sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - make
      - python-pip
install:
  - pip install gitchangelog
  - pip install pystache
  - make setup
script:
  - make test